"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, Building2, Cable, LayoutDashboard, Wrench } from "lucide-react";
import { authFetch } from "../lib/api";
import { useLocale } from "../i18n/LocaleProvider";

type Mode = "dashboard"|"devices"|"sites"|"incidents"|"maintenance"|"addresses"|"topology";
type Row = Record<string, unknown>;
const nav = [["/reseau","network.dashboard",LayoutDashboard],["/reseau/equipements","network.devices",Cable],["/reseau/sites","network.sites",Building2],["/reseau/adresses","network.conflicts",AlertTriangle],["/reseau/incidents","network.incidents",AlertTriangle],["/reseau/maintenance","network.maintenance",Wrench]] as const;
async function json(path:string,init?:RequestInit){const r=await authFetch(path,init);const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||"Erreur serveur.");return d;}

export default function NetworkModule({mode}:{mode:Mode}){
  const {t}=useLocale(); const [data,setData]=useState<any>(null);const [devices,setDevices]=useState<Row[]>([]);const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setMessage("");try{const path=mode==="dashboard"?"/network/dashboard":mode==="devices"?"/network/devices":mode==="sites"?"/network/sites":mode==="incidents"?"/network/incidents":mode==="maintenance"?"/network/maintenance":mode==="addresses"?"/network/conflicts":"/network/devices";setData(await json(path));if(["incidents","maintenance","topology"].includes(mode))setDevices(await json("/network/devices"));}catch(e){setMessage(e instanceof Error?e.message:"Erreur de chargement.");}finally{setLoading(false);}},[mode]);useEffect(()=>{void load();},[load]);
  async function submit(e:FormEvent<HTMLFormElement>,path:string){e.preventDefault();const f=new FormData(e.currentTarget);try{await json(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f.entries()))});e.currentTarget.reset();setMessage("Enregistré avec succès.");await load();}catch(er){setMessage(er instanceof Error?er.message:"Enregistrement impossible.");}}
  const rows=Array.isArray(data)?data:[];
  return <main className="min-h-screen bg-slate-100 p-3 text-slate-900 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl"><header className="rounded-3xl bg-indigo-950 p-6 text-white shadow-xl"><p className="font-bold text-sky-300">MaliLink</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">{t("network.title")}</h1><p className="mt-2 text-indigo-100">Inventaire, adressage, incidents et supervision explicite — aucun état en ligne n’est simulé.</p></header><nav className="mt-4 flex gap-2 overflow-x-auto pb-2">{nav.map(([h,k,I])=><Link key={h} href={h} className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold shadow"><I className="h-4 w-4"/>{t(k)}</Link>)}</nav>{message&&<p className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 font-semibold">{message}</p>}{loading?<p className="mt-8">{t("common.loading")}</p>:<section className="mt-5">
    {mode==="dashboard"&&data&&<div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Équipements",data.devices?.total],["En ligne",data.devices?.online],["Hors ligne",data.devices?.offline],["Inconnus",data.devices?.unknown],["Incidents ouverts",data.incidents?.open],["Maintenances à venir",data.maintenance?.upcoming],["Conflits IP",data.ip_conflicts]].map(([l,v])=><article key={String(l)} className="rounded-2xl bg-white p-4 shadow"><p className="text-xs font-bold uppercase text-slate-500">{l}</p><p className="mt-2 text-2xl font-black">{String(v??0)}</p></article>)}</div>}
    {mode==="devices"&&<><Table rows={rows} cols={["name","category","site_name","ip_address","mac_address","vlan","status","last_checked_at"]}/><form onSubmit={e=>submit(e,"/network/devices")} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 shadow sm:grid-cols-2"><h2 className="text-xl font-black sm:col-span-2">Ajouter un équipement</h2><input name="name" required placeholder="Nom" className="rounded-xl border p-3"/><select name="category" required className="rounded-xl border p-3"><option value="">Catégorie</option>{["router","switch","access_point","firewall","server","nas","nvr","dvr","camera","printer","computer","phone","ups","other"].map(x=><option key={x}>{x}</option>)}</select>{["manufacturer","model","serial_number","ip_address","mac_address","vlan","ssid","switch_port","rack_location","firmware_version"].map(x=><input key={x} name={x} placeholder={x} className="rounded-xl border p-3"/>)}<select name="monitoring_type" className="rounded-xl border p-3"><option value="none">Pas de sonde</option><option value="http">HTTP</option><option value="https">HTTPS</option></select><button className="rounded-xl bg-indigo-800 p-3 font-bold text-white">Enregistrer</button></form></>}
    {mode==="sites"&&<><Table rows={rows} cols={["code","name","address","responsible_name","status"]}/><form onSubmit={e=>submit(e,"/network/sites")} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 shadow sm:grid-cols-2"><h2 className="text-xl font-black sm:col-span-2">Ajouter un site</h2>{["code","name","address","responsible_name"].map(x=><input key={x} name={x} required={["code","name"].includes(x)} placeholder={x} className="rounded-xl border p-3"/>)}<button className="rounded-xl bg-indigo-800 p-3 font-bold text-white">Enregistrer</button></form></>}
    {mode==="addresses"&&<Table rows={rows} cols={["ip_address","count","devices"]}/>} 
    {mode==="incidents"&&<><Table rows={rows} cols={["title","severity","status","device_name","site_name","opened_at"]}/><form onSubmit={e=>submit(e,"/network/incidents")} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 shadow sm:grid-cols-2"><h2 className="text-xl font-black sm:col-span-2">Ouvrir un incident</h2><input name="title" required placeholder="Titre" className="rounded-xl border p-3"/><select name="device_id" className="rounded-xl border p-3"><option value="">Équipement</option>{devices.map(d=><option key={String(d.id)} value={String(d.id)}>{String(d.name)}</option>)}</select><select name="severity" className="rounded-xl border p-3"><option>low</option><option>medium</option><option>high</option><option>critical</option></select><textarea name="description" placeholder="Description" className="rounded-xl border p-3 sm:col-span-2"/><button className="rounded-xl bg-indigo-800 p-3 font-bold text-white">Créer</button></form></>}
    {mode==="maintenance"&&<><Table rows={rows} cols={["device_name","maintenance_type","scheduled_for","status","cost"]}/><form onSubmit={e=>submit(e,"/network/maintenance")} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 shadow sm:grid-cols-2"><h2 className="text-xl font-black sm:col-span-2">Planifier une maintenance</h2><select name="device_id" required className="rounded-xl border p-3"><option value="">Équipement</option>{devices.map(d=><option key={String(d.id)} value={String(d.id)}>{String(d.name)}</option>)}</select><input name="maintenance_type" placeholder="Type" className="rounded-xl border p-3"/><input name="scheduled_for" type="datetime-local" className="rounded-xl border p-3"/><input name="cost" type="number" step="any" placeholder="Coût" className="rounded-xl border p-3"/><textarea name="description" placeholder="Description" className="rounded-xl border p-3 sm:col-span-2"/><button className="rounded-xl bg-indigo-800 p-3 font-bold text-white">Planifier</button></form></>}
    {mode==="topology"&&<div className="rounded-2xl bg-white p-6 shadow"><h2 className="text-xl font-black">Topologie logique</h2><p className="mt-2 text-slate-600">La documentation des liaisons est préparée. Aucun scan automatique n’est lancé. Équipements connus : {devices.length}.</p></div>}
  </section>}</div></main>;
}
function Table({rows,cols}:{rows:Row[];cols:string[]}){return <div className="overflow-x-auto rounded-2xl bg-white shadow"><table className="min-w-full text-sm"><thead className="bg-indigo-950 text-white"><tr>{cols.map(c=><th key={c} className="whitespace-nowrap p-3 text-left">{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)} className="border-t">{cols.map(c=><td key={c} className="max-w-xs whitespace-nowrap p-3">{typeof r[c]==="object"?JSON.stringify(r[c]):String(r[c]??"—")}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-slate-500">Aucune donnée.</p>}</div>}
